### ISSUE TITLE
Get a plot as a string

### ISSUE THREAD

**Issue by JoshKarpel** [olavolav/uniplot#10]
I'm working on a tool that I would love to be able to integrate `uniplot` into, but I'm running into a problem: I need to capture the output as a string so that I can display it elsewhere. Right now, `uniplot.plot` prints directly to stdout: https://github.com/olavolav/uniplot/blob/master/uniplot/uniplot.py#L74

I'm not sure how to square this with the interactive features implemented in that function. Perhaps a helper function could be extracted that returns the plot as a string? Then I could call that function from my tool to get the string that `uniplot.plot` would have displayed.

Happy to do the work on this if you can provide some guidance on how you'd like it implemented!

**Comment by olavolav** [comment]
Hi @JoshKarpel thanks for the request!

Should be possible fairly easily. So let's say you had a function `plot_to_string` that has the same signature as `plot` but without the `interactive` option, would that help already?

In particular right now uniplot does not guarantee a horizontal dimension, as width is the `width` option plus how much space the vertical axis labels take. Depending on how you want to integrate the output, would that be an issue for you?

**Comment by JoshKarpel** [comment]
> So let's say you had a function `plot_to_string` that has the same signature as `plot` but without the `interactive` option, would that help already?

Definitely!
 
> In particular right now uniplot does not guarantee a horizontal dimension, as width is the `width` option plus how much space the vertical axis labels take. Depending on how you want to integrate the output, would that be an issue for you?

I don't think it's a deal breaker, but it might make things easier. I could certainly do without it for first pass!

My current thinking is that I'll probably be sticking the plot output inside a https://rich.readthedocs.io/en/stable/reference/text.html#rich.text.Text , and I can disable wrapping - but that means the plot might get cut off if I don't guess the width right.

**Comment by olavolav** [comment]
Thanks @JoshKarpel!

I'll have a look over the weekend, but I think it shouldn't be too hard, might actually end up with more readable code when splitting the plot generation and text output.

I also thought about limiting the bounding box of the plot, this should also be possible by computing the vertical axis labels first, and then shrinking the plot window if needed. But I'll leave this for a later date.

**Comment by olavolav** [comment]
Hi @JoshKarpel I just added such a function in version `0.4.4` 🚢 

Haven't gotten around to do the "hard cap on line length" part yet, but hope this helps already.

If you can share I'd be curious to see what you end up with on your side!

**Comment by JoshKarpel** [comment]
> Hi @JoshKarpel I just added such a function in version `0.4.4` 🚢
> 
> Haven't gotten around to do the "hard cap on line length" part yet, but hope this helps already.
> 
> If you can share I'd be curious to see what you end up with on your side!

It's working really well so far! https://github.com/JoshKarpel/spiel/pull/33/files

![image](https://user-images.githubusercontent.com/7133863/118376818-f036b500-b58f-11eb-8c6a-990f8fcd1bfe.png)

**Comment by olavolav** [comment]
Very cool! 😄 Looking forward to see how Spiel progresses

**Comment by NikosAlexandris** [comment]
> Hi @JoshKarpel I just added such a function in version `0.4.4` 🚢
> 
> Haven't gotten around to do the "hard cap on line length" part yet, but hope this helps already.
> 
> If you can share I'd be curious to see what you end up with on your side!

I missed to read that

> There is also a plot_to_string function with the same signature, if you want the result as a list of strings, to include the output elsewhere. The only difference is that plot_to_string does not support interactive mode.

under [Parameters](https://github.com/olavolav/uniplot/tree/master?tab=readme-ov-file#parameters).  Exactly what I also need !

@olavolav  May I suggest to move this text or else mention this magical function under [Features](https://github.com/olavolav/uniplot/tree/master?tab=readme-ov-file#features) ?

**Comment by NikosAlexandris** [comment]
@JoshKarpel Can I copy your code at https://github.com/JoshKarpel/spiel/pull/33/commits/bd64b7f2f04bdbe15c081360990ec6d4c93f0141#diff-d49034a4cceaaf506672cb643df400c46e05f585099f0e8b8850ff2d66e2eaf1 and reuse ? It's [MIT licensed](https://github.com/JoshKarpel/spiel/blob/main/LICENSE).  Any particular form to give you credit ?

ps- This will save time from essentially exploring how to do what you did.-

**Comment by JoshKarpel** [comment]
> @JoshKarpel Can I copy your code at [JoshKarpel/spiel@bd64b7f#diff-d49034a4cceaaf506672cb643df400c46e05f585099f0e8b8850ff2d66e2eaf1](https://github.com/JoshKarpel/spiel/commit/bd64b7f2f04bdbe15c081360990ec6d4c93f0141#diff-d49034a4cceaaf506672cb643df400c46e05f585099f0e8b8850ff2d66e2eaf1) and reuse ? It's [MIT licensed](https://github.com/JoshKarpel/spiel/blob/main/LICENSE). Any particular form to give you credit ?
> 
> ps- This will save time from essentially exploring how to do what you did.-

The license defines the terms for copying and reusing the code.

**Comment by NikosAlexandris** [comment]
Dear @JoshKarpel, did you ever have to deal with "misaligned" content fed to a Rich Panel ? Like 

``` shell
╭──────────────────────────────────────────────────────────╮
│                      Horizon height                      │
│     ┌─────────────────────────────────────────────┐      │
│   │  ⣠⠤⠒⠒⠒⠒⠒⠒⠒⠊⠉⠉⠉⠉⠒⠤⣀⣀⣀⡄   ⢀⡀⣀⠤⠔⠒⠉⠉⠦⡀          │ 0.4    │
│     │⡠⠊                   ⠈⠑⠒⠊⠁⠈       ⠈⠓⠢⣀       │      │
│   │                                      ⠉⠉⠉⠒⠒⢄⡠│ 0.2    │
│     └─────────────────────────────────────────────┘      │
│          0          100         200          300         │
│                           ⣿⣿ Horizon Profile             │
╰───────────────────────────────── Horizon height profile ─╯
```

**Comment by JoshKarpel** [comment]
> Dear @JoshKarpel, did you ever have to deal with content "misaligned" when fed to a Rich Panel ? Like
> 
> ```shell
> ╭──────────────────────────────────────────────────────────╮
> │                      Horizon height                      │
> │     ┌─────────────────────────────────────────────┐      │
> │   │  ⣠⠤⠒⠒⠒⠒⠒⠒⠒⠊⠉⠉⠉⠉⠒⠤⣀⣀⣀⡄   ⢀⡀⣀⠤⠔⠒⠉⠉⠦⡀          │ 0.4    │
> │     │⡠⠊                   ⠈⠑⠒⠊⠁⠈       ⠈⠓⠢⣀       │      │
> │   │                                      ⠉⠉⠉⠒⠒⢄⡠│ 0.2    │
> │     └─────────────────────────────────────────────┘      │
> │          0          100         200          300         │
> │                           ⣿⣿ Horizon Profile             │
> ╰───────────────────────────────── Horizon height profile ─╯
> ```

It's been a long time since I looked at this stuff, but I suspect the problem might be around ensuring that all control characters are correctly accounted for. Looking at the `repr` of the output string might help.

**Comment by NikosAlexandris** [comment]
Alright, this one I solved quickly. Your short feedback did help me though.  The problem was "centering" inside a Rich Table which was put inside a Panel.  But I have more of this problems to solve, in a documentation built in GitLab CI context.
