### ISSUE TITLE
Feature request: Boxplot

### ISSUE THREAD

**Issue by Chaitanyabsprip** [olavolav/uniplot#12]
I'd like to plot boxplots on the terminal along with support for multiple boxplots alongside other boxplots

**Comment by olavolav** [comment]
So something like this, right? https://en.wikipedia.org/wiki/Box_plot#/media/File:Michelsonmorley-boxplot.svg

To be honest I'm not sure if the resolution of the terminal is good enough for this. Maybe simple error bars?

If you want you can check out the `histogram` function to get an idea of the challenge here.

Let me know what you think, or if you want to try to build it yourself.

**Comment by Chaitanyabsprip** [comment]
will get back to you after trying it myself once.

**Comment by olavolav** [comment]
Sounds good 👍 Closing for now, let me know once you are ready
