### ISSUE TITLE
Missing link to repository on PyPI page

### ISSUE THREAD

**Issue by adigitoleo** [olavolav/uniplot#25]
I'm not familiar with poetry, but in standard python projects this would be fixed by setting the following in `pyproject.toml`:

```
[project.urls]
repository = "https://github.com/olavolav/uniplot"
documentation = <docs website, if any>
```

Just a small gripe

**Comment by olavolav** [comment]
Thanks @adigitoleo for the heads-up, I'll fix that shortly

**Comment by olavolav** [comment]
Ah didn't mean to auto-close it. Let's see if it works first

**Comment by olavolav** [comment]
Yes, looking good now:

![Bildschirmfoto 2024-03-24 um 12 14 06](https://github.com/olavolav/uniplot/assets/340835/a202d1fc-8746-4f94-a10f-191f455d1c88)

Closing this issue ✅
