### ISSUE TITLE
Use different characters instead of colors 

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [olavolav/uniplot#27]
Is is possible to use different characters instead of colors for plotting multiple series?

It would be nice because I use this library for plotting, and then redirect the python script output to a file, which obviously loses the concept of color, so using like "*" and "+" instead of colors you be nice

**Comment by olavolav** [comment]
Hi @AlbertoSinigaglia thanks for the suggestion!

This would be possible, but I imagine only for the `force_ascii` mode. At least it is less clear how to implement this using the default high-resolution mode via Unicode characters.

Is that what you mean, do you set `force_ascii=True` in the plots that you speak about?

**Comment by AlbertoSinigaglia** [comment]
> Hi @AlbertoSinigaglia thanks for the suggestion!
> 
> 
> 
> This would be possible, but I imagine only for the `force_ascii` mode. At least it is less clear how to implement this using the default high-resolution mode via Unicode characters.
> 
> 
> 
> Is that what you mean, do you set `force_ascii=True` in the plots that you speak about?


Hi, thanks for the reply, yes, I actually use that flag to be sure to avoid compatibility issues

**Comment by olavolav** [comment]
@AlbertoSinigaglia With version v0.13.1 this is now possible. You can control the characters used with the `force_ascii_characters` option.
