### ISSUE TITLE
plot fails when multiseries is provided with empty list

### ISSUE THREAD

**Issue by PabloRuizCuevas** [olavolav/uniplot#30]
In my use-case the list of numbers are dynamically generated, which sometimes create something like this:

```python
plot([[1,2,3,4,3,2,3,4],[3,2,2,4,1,2,1,4],[1,3],[]], lines=True)
```

Which fails, i think during validation, extracting the max. It also happens with x,y data (which is actually my case).

Looking at the logic I think probably is wise to exclude them from the multi series, but that may also interact with the colors, other possible solution is changing some functions like:

```python
def y_max(self) -> float:
    return max([_safe_max(ys_row) for ys_row in self.ys])

#to

def y_max(self) -> float:
    return max([_safe_max(ys_row) for ys_row in self.ys if len(self.ys) >0])
```

**Comment by olavolav** [comment]
Fixed in new release [v0.12.7](https://github.com/olavolav/uniplot/releases/tag/v0.12.7).
