### ISSUE TITLE
On `force_ascii` and support for Unicode characters

### ISSUE THREAD

**Issue by NikosAlexandris** [olavolav/uniplot#32]
The `force_ascii` option is useful, reportedly, to _Force ASCII characters for plotting only. This can be useful for compatibility, for example when using uniplot inside of CI/CD systems that do not support Unicode. Defaults to False._

I am fighting with this : I still can't get  a regularly looking output, executed commands from inside a [markdown-exec](https://pawamoy.github.io/markdown-exec/) executable code block.

Finally, and however, I got to access a docker image where I can update locales, etc. I am trying to install some fonts and set `LC_ALL` etc., but I still cannot get the output appear as expected. See also  : https://github.com/pawamoy/markdown-exec/discussions/45#discussioncomment-9217987. What can I do to ensure uniplot/s are rendered correctly ?

**Comment by olavolav** [comment]
Hi @NikosAlexandris could you post an example of the uniplot function you are calling, and the output you are seeing?

With `force_ascii=True` and perhaps `color=False` you should not have any problems, but I'd be curious to see your case

**Comment by NikosAlexandris** [comment]
> Hi @NikosAlexandris could you post an example of the uniplot function you are calling, and the output you are seeing?
> 
> With `force_ascii=True` and perhaps `color=False` you should not have any problems, but I'd be curious to see your case

Thank you for the reply. Struggling here to understand how I should set up the CI/CD environment to make things looks okay. Locally, I see no problems. "Remotely" I see things (exactly actually) like in this page : https://nikosalexandris.github.io/rekx/how_to/help/#help (see end of code block `rekx --help`).

I have even set now both locally and for CI/CD build (not the `rekx` example above, but another project) 

``` yaml
theme:
  font: false
```
in `mkdocs.yml`.

For Uniplot/s, I use something like

``` python
    import shutil
    from functools import partial
    from uniplot import plot as default_plot

    terminal_columns, _ = shutil.get_terminal_size()  # we don't need lines!
    terminal_length = int(terminal_columns * terminal_width_fraction)
    plot = partial(default_plot, width=terminal_length)
```

then using this somewhere
``` python
# some code
        plot(
            # xs=timestamps,
            ys=y_series,
            legend_labels=legend_labels,
            lines=lines,
            title=title if title else supertitle,
            y_unit=' ' + str(unit),
            # force_ascii=True,
        )
```
to renders plots fine locally (with or without explicitly `export FORCE_COLOR=1`)

![2024-06-25T22:11:35,176280794+03:00](https://github.com/olavolav/uniplot/assets/7046639/b181be75-3da3-4885-846f-f97fc0f0cf1d)

but not when the documentation is build through the CI/CD image

![image](https://github.com/olavolav/uniplot/assets/7046639/6844671f-6f7d-45f4-a9c9-bd175b6cdc75)

**Comment by olavolav** [comment]
It does look like a font issue. Could you try 2 things:

1. Use `force_ascii=True`, then the output should display identically. Though of course you loose the Unicode-powered high resolution.
2. Use `color=False` and see what you get.

Thanks!

**Comment by NikosAlexandris** [comment]
> It does look like a font issue. Could you try 2 things:
> 
>     1. Use `force_ascii=True`, then the output should display identically. Though of course you loose the Unicode-powered high resolution.
> 
>     2. Use `color=False` and see what you get.
> 
> 
> Thanks!

@olavolav This is about `uniplot` and `color=False`, and not about the problem I am trying to resolve.

While testing locally, I get

![2024-07-01T08:39:05,574824007+03:00](https://github.com/olavolav/uniplot/assets/7046639/e14b80e1-d407-49cc-b258-21a3440ce2a4)

Maybe the "legend" slips away the `color=False` option ?

**Comment by olavolav** [comment]
@NikosAlexandris Thanks for pointing this out! Indeed, that's not correct behavior, have opened #33 to track that. I have a fix locally already.

**Comment by olavolav** [comment]
@NikosAlexandris Now that #33 is closed, can we close this ticket here as well?

**Comment by olavolav** [comment]
@NikosAlexandris Closing this for now, let me now if there is anything else you need.

**Comment by NikosAlexandris** [comment]
Thank you, it works.

![2024-08-31T14:44:59,774855425+03:00](https://github.com/user-attachments/assets/ee8c427e-bd47-4402-b845-873058338853)

Multiple all-white series are then not easy (or possible) to differentiate.  Adding `force_ascii=True` does the following 

![2024-08-31T14:46:27,665289180+03:00](https://github.com/user-attachments/assets/e6ee8a18-b967-41cc-833e-ada13bbaf4d0)

The combination of `color=False` and multiple series should _maybe force_ `force_ascii=True` ?
