### ISSUE TITLE
Support for polar plots

### ISSUE THREAD

**Issue by NikosAlexandris** [olavolav/uniplot#37]
Can we get support for polar plots ? 

To start with and based on https://github.com/tfpgh/polar_ascii

and then

``` python
import math

# Domain of theta: from -π to π
domain: tuple[float, float] = (-math.pi, math.pi)

# Function to generate a circle with a given radius
def r(theta: float, radius: float = 1) -> float:
    return radius
```

and a somewhat modified version of the original [polar_ascii.py](https://github.com/tfpgh/polar_ascii/blob/214229c66c554335fb35c535ff2fb768102e4da4/polar_ascii.py) script gist-ed here : https://gist.github.com/NikosAlexandris/4cead432137f3a74c5e3ef3a4ddf9377

we can have something like
``` shell
          @ @ @ @ @ @ @ @
      @ @ @             @ @ @
    @ @                     @ @
    @                         @
  @ @                         @ @
  @                             @
@ @                             @ @
@                                 @
@                                 @
@                                 @
@ @                             @ @
  @                             @
  @ @                         @ @
    @                         @
    @ @                     @ @
      @ @ @             @ @ @
          @ @ @ @ @ @ @ @
```

**Comment by olavolav** [comment]
Hi @NikosAlexandris I guess there are two options here:

1.) Ask the user to do the conversion themselves, like so:
```python3
import numpy as np
from uniplot import plot
rads = np.linspace(0, 2*np.pi)
xs = np.cos(rads)
ys = np.sin(rads)
plot(xs=xs, ys=ys, lines=True, width=40, height=20, x_gridlines=[], y_gridlines=[])
```
yields
```
┌────────────────────────────────────────┐
│           ▗▄▄▀▀▀▀▀▀▀▀▀▀▀▀▄▄▖           │ 1
│        ▄▞▀▘                ▝▀▚▄        │
│      ▄▀                        ▀▄      │
│    ▄▀                            ▀▄    │
│  ▗▞                               ▝▚▖  │
│ ▗▘                                  ▀▖ │
│ ▞                                    ▚ │
│▐                                      ▌│
│▌                                      ▐│
│▌                                      ▐│ 0
│▌                                      ▐│
│▌                                      ▐│
│▐                                      ▌│
│ ▚                                    ▞ │
│ ▝▖                                  ▄▘ │
│  ▝▚                               ▗▞▘  │
│    ▀▄                            ▄▀    │
│      ▀▄                        ▄▀      │
│        ▀▚▄▖                ▗▄▞▀        │
│           ▝▀▀▄▄▄▄▄▄▄▄▄▄▄▄▀▀▘           │ -1
└────────────────────────────────────────┘
                    0                   1
```

2.) Or we could have something like [matplotlib's polar projections](https://matplotlib.org/stable/api/projections/polar.html#module-matplotlib.projections.polar). That might be a bit much for our little library here, and perhaps is better placed in surrounding code?

The use case here is artistically, did I get that right?

**Comment by NikosAlexandris** [comment]
> Hi @NikosAlexandris I guess there are two options here:
> 
> 1.) Ask the user to do the conversion themselves, like so:
> 
> ```python
> import numpy as np
> from uniplot import plot
> rads = np.linspace(0, 2*np.pi)
> xs = np.cos(rads)
> ys = np.sin(rads)
> plot(xs=xs, ys=ys, lines=True, width=40, height=20, x_gridlines=[], y_gridlines=[])
> ```
> 
> yields
> 
> ```
> ┌────────────────────────────────────────┐
> │           ▗▄▄▀▀▀▀▀▀▀▀▀▀▀▀▄▄▖           │ 1
> │        ▄▞▀▘                ▝▀▚▄        │
> │      ▄▀                        ▀▄      │
> │    ▄▀                            ▀▄    │
> │  ▗▞                               ▝▚▖  │
> │ ▗▘                                  ▀▖ │
> │ ▞                                    ▚ │
> │▐                                      ▌│
> │▌                                      ▐│
> │▌                                      ▐│ 0
> │▌                                      ▐│
> │▌                                      ▐│
> │▐                                      ▌│
> │ ▚                                    ▞ │
> │ ▝▖                                  ▄▘ │
> │  ▝▚                               ▗▞▘  │
> │    ▀▄                            ▄▀    │
> │      ▀▄                        ▄▀      │
> │        ▀▚▄▖                ▗▄▞▀        │
> │           ▝▀▀▄▄▄▄▄▄▄▄▄▄▄▄▀▀▘           │ -1
> └────────────────────────────────────────┘
>                     0                   1
> ```

That looks nice. And easier than I thought, it seems !

> 2.) Or we could have something like [matplotlib's polar projections](https://matplotlib.org/stable/api/projections/polar.html#module-matplotlib.projections.polar). That might be a bit much for our little library here, and perhaps is better placed in surrounding code?

This would be indeed _much_. Maybe.

> The use case here is artistically, did I get that right?

Actually, I want to plot a horizon profile, something like in 

![horizon_45 986_8 186](https://github.com/user-attachments/assets/ddd8deb7-100a-46fd-ae16-be3a1fc34313)

> Source : https://re.jrc.ec.europa.eu/pvg_tools/en/

**Comment by olavolav** [comment]
Glad that it was helpful! The horizon profile is a cool project, too

Let's conclude to go with (1.) for the time being

**Comment by NikosAlexandris** [comment]
I've spent hours refreshing once again trigonometry. No GPT support. To get thins right for the followine "experiments" (the hard way), I got some help from some trigonometry expert in the end 😄 . 

Quite a brainjogging... but it has to be

``` python
# Generate equidistant azimuthal directions, say 64 + 1
azimuthal_directions_degrees = numpy.linspace(0, 360, 65)
azimuthal_directions_radians = numpy.radians(azimuthal_directions_degrees)
x_azimuth = numpy.sin(azimuthal_directions_radians)
y_azimuth = numpy.cos(azimuthal_directions_radians)
```
since we measure (usually, most ?) geographic azimuth from North = 0.

An example of what I want to get out (see source for this and few more : https://gist.github.com/NikosAlexandris/28c889ee19df3d9b414271f66fcd5a88 ) : 

``` bash
North
┌─────────────────────────────────────────────┐
│▌                                           ▐│ 20
│▌                                           ▐│
│▌                                           ▐│
│▌                                           ▐│
│▐                                           ▌│
│▐▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▌│ 0
└─────────────────────────────────────────────┘
 0          100         200          300
                 ██ North fin
┌─────────────────────────────────────────────┐
│             ▄▄▞▀▀▀▀▚▀▀▀▞▀▀▀▀▚▄▄             │ 1
│         ▄▄▀▀        ▌ ▐        ▀▀▄▄         │
│      ▗▞▀            ▐ ▌            ▀▚▖      │
│    ▗▞▘               █               ▝▚▖    │
│   ▟▘                                   ▝▙   │
│  ▞                                       ▚  │
│ ▞                                         ▚ │
│▗▘                                         ▝▖│
│▌                                           ▐│
│▌                                           ▐│ 0
│▌                                           ▐│
│▌                                           ▐│
│▝▖                                         ▗▘│
│ ▚                                         ▞ │
│  ▚                                       ▞  │
│   ▜▖                                   ▗▛   │
│    ▝▚▖                               ▗▞▘    │
│      ▝▚▄                           ▄▞▘      │
│         ▀▀▄▄                   ▄▄▀▀         │
│             ▀▀▚▄▄▄▄▄▄▄▄▄▄▄▄▄▞▀▀             │ -1
└─────────────────────────────────────────────┘
-1                     0                     1
                 ██ Horizon
                 ██ North fin

Before East
┌─────────────────────────────────────────────┐
│         ▐▜                                  │ 20
│         ▐▐                                  │
│         ▐▐                                  │
│         ▌▝▖                                 │
│         ▌ ▌                                 │
│▄▄▄▄▄▄▄▄▄▌ ▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄│ 0
└─────────────────────────────────────────────┘
 0          100         200          300
              ██ Before East fin
┌─────────────────────────────────────────────┐
│             ▄▄▞▀▀▀▀▀▀▀▀▀▀▀▀▀▚▄▄             │ 1
│         ▄▄▀▀                   ▀▀▄▄         │
│      ▗▞▀                           ▀▚▖      │
│    ▗▞▘                               ▝▚▖    │
│   ▟▘                                   ▝▙   │
│  ▞                                       ▚  │
│ ▞                                         ▚ │
│▗▘                                   ▄▄▄▄▀▀▀▖│
│▌                                   ▜       ▐│
│▌                                   ▝▀▀▀▀▄▄▄▄│ 0
│▌                                           ▐│
│▌                                           ▐│
│▝▖                                         ▗▘│
│ ▚                                         ▞ │
│  ▚                                       ▞  │
│   ▜▖                                   ▗▛   │
│    ▝▚▖                               ▗▞▘    │
│      ▝▚▄                           ▄▞▘      │
│         ▀▀▄▄                   ▄▄▀▀         │
│             ▀▀▚▄▄▄▄▄▄▄▄▄▄▄▄▄▞▀▀             │ -1
└─────────────────────────────────────────────┘
-1                     0                     1
              ██ Horizon
              ██ Before East fin
East
```

Trying to generalise a function for my use-case now.

**Comment by olavolav** [comment]
Very cool!

**Comment by olavolav** [comment]
One idea: If for these plots you need a bit of finer resolution your can try the `character_set="braille"` option that was added in v0.15.0.

**Comment by NikosAlexandris** [comment]
> `character_set="braille"`

That's a game-changer !

**Comment by olavolav** [comment]
I definitely think others might be interested in the health profiles as well. In terms of where to put it, I think use-case specific code should be in a separate repository. How about you start a separate health profile repo? You could either have a library that does the calculation as well as plotting, or it's even something specific to health profile plotting that extends uniplot?

**Comment by NikosAlexandris** [comment]
> Actually, I want to plot a horizon profile, something like in
> 
> ![horizon_45 986_8 186](https://private-user-images.githubusercontent.com/7046639/397006455-ddd8deb7-100a-46fd-ae16-be3a1fc34313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTM0MDIsIm5iZiI6MTczNTgxMzEwMiwicGF0aCI6Ii83MDQ2NjM5LzM5NzAwNjQ1NS1kZGQ4ZGViNy0xMDBhLTQ2ZmQtYWUxNi1iZTNhMWZjMzQzMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDJUMTAxODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJkMGFkZmQ0Mjg2OTA5Y2FjMGFiMGQyOWY0ZDE2NDk4MDNhZjE0ZDQ4NTM1Y2RkMWJlMDQxMTY1Yjc0MDFiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XmopHY417Scx7yTiw62rqnvVuwPZWb2BXrgz9vC6tB4)
> 
> > Source : https://re.jrc.ec.europa.eu/pvg_tools/en/

I've progressed quite a bit.  An (partial) example here : 

![2025-01-02T11:20:44,177024620+01:00](https://github.com/user-attachments/assets/d1b50c16-cc84-46f5-8495-b0fa3686add9)

I only miss to : 

1. "fill" the area between the outer circle (cyan) and the inner one (yellow).

2. find a way to place labels for the cardinal directions and (hopefully easily) the degrees inside the polar plot, like in the PVGIS example above.

**Comment by NikosAlexandris** [comment]
> I definitely think others might be interested in the health profiles as well. In terms of where to put it, I think use-case specific code should be in a separate repository. How about you start a separate health profile repo? You could either have a library that does the calculation as well as plotting, or it's even something specific to health profile plotting that extends uniplot?

Olav

it's height values around a geographic location measured upwards as angles from the horizontal plane (ground). It'll be part of a bigger project, first.  Then, yes, it can become a mini stand-alone project.  In the context of uniplot, I think this examples opens-up polar plots in general, useful (at least) for anything (?) involving angles.

**Comment by NikosAlexandris** [comment]
Given three inputs, would it be hard to somehow let  `character_set=["braille", "*", "+"]` work as a list corresponding to `x` and `y` input lists ?

**Comment by NikosAlexandris** [comment]
And a short asciinema to support the use-case : https://asciinema.org/a/pynlwepKNRE6gqKqwPr6JmzTP.

**Comment by olavolav** [comment]
@NikosAlexandris done ✅
