### ISSUE TITLE
Missing precision on x axis values, making them identical

### ISSUE THREAD

**Issue by AntoineSto** [olavolav/uniplot#5]
Hello Olav,
I have noticed a small problem when displaying the x axis values. The values seem to be rounded too much making them identical and equal to 0. It seems to happen when one value is positive, the other negative and the values are close to 0 (+-0.01) I included screenshots of it.

PS: uniplot feels great, keep it up!

<img width="485" alt="Screenshot 2021-01-22 at 16 58 48" src="https://user-images.githubusercontent.com/77641894/105513906-2eebeb00-5cd3-11eb-85f2-a12459ffa215.png">

<img width="481" alt="Screenshot 2021-01-22 at 17 08 59" src="https://user-images.githubusercontent.com/77641894/105515056-8c346c00-5cd4-11eb-9024-f2186af65b92.png">

**Comment by olavolav** [comment]
You're right, thanks for this issue, and glad that you enjoy uniplot! 😄

Indeed the numbers are rounded too much, the comparison thinks they are different enough due to the different sign, which doesn't make sense here. I'll think of something.

**Comment by olavolav** [comment]
So I have a fix and will publish it later.

I've actually played around with the idea of adding more sophisticated axis labels as in [Talbot, J., Lin, S. & Hanrahan, P. An Extension of Wilkinson’s Algorithm for Positioning Tick Labels on Axes. IEEE T Vis Comput Gr 16, 1036–1043 (2010)](https://ieeexplore.ieee.org/document/5613441) but this will still take some time to get right.

**Comment by olavolav** [comment]
@AntoineSto Just for your information, I finally finished and pushed the nicer axis labels yesterday 😄
